apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8wp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8wp
  template:
    metadata:
      labels:
        app: k8wp
    spec:
      containers:
      - name: php-container
        image: alaric123/k8wp
        ports:
        - containerPort: 80
